Repository LD4P/sinopia_profile_editor, pull requests merged in 2019-05, with the labels that each got.

#209 Fetch Help and Resources menu content from github pages
  source/index.html
Labels: M3, needs review

#213 fix broken build; fix false positives in tests; update dependencies
  .circleci/config.yml
  .eslintrc-todo.yml
  .eslintrc.yml
  Gruntfile.js
  README.md
  package-lock.json
  package.json
  source/__tests__/integration/create-ontologies.test.js
  source/__tests__/integration/create-profile.test.js
  source/__tests__/integration/create-property.test.js
  source/__tests__/integration/create-resource.test.js
  source/__tests__/integration/empty-profile-export.test.js
  source/__tests__/integration/export-profile.test.js
  source/__tests__/integration/home-page.test.js
  source/__tests__/integration/import-profile.test.js
  source/__tests__/integration/new-profile.test.js
  source/__tests__/integration/off-canvas-menu.test.js
  source/__tests__/integration/profile-create.test.js
  source/__tests__/integration/property-types.test.js
  source/__tests__/versoSpoof.test.js
Labels: needs review

#217 tests hopefully pass more often
  .eslintrc.js
  README.md
  package.json
  source/__tests__/integration/create-ontologies.test.js
  source/__tests__/integration/create-profile.test.js
  source/__tests__/integration/create-property.test.js
  source/__tests__/integration/create-resource.test.js
  source/__tests__/integration/export-profile.test.js
  source/__tests__/integration/home-page.test.js
  source/__tests__/integration/import-profile.test.js
  source/__tests__/integration/jestPuppeteerHelper.js
  source/__tests__/integration/new-profile.test.js
  source/__tests__/integration/profile-create.test.js
  source/__tests__/integration/property-types.test.js
Labels: M3

#218 fix deployment header links so they reflect the environment they are in (dev, staging, prod)
  source/__tests__/integration/home-page.test.js
  source/__tests__/integration/jestPuppeteerHelper.js
  source/__tests__/integration/off-canvas-menu.test.js
  source/__tests__/integration/profile-create.test.js
  source/index.html
Labels: M3

#219 add tests for off-canvas menu and refactor tests
  source/__tests__/integration/footer.test.js
  source/__tests__/integration/header.test.js
  source/__tests__/integration/home-page.test.js
  source/__tests__/integration/import-profile.test.js
  source/__tests__/integration/jestPuppeteerHelper.js
  source/__tests__/integration/off-canvas-menu.test.js
  source/__tests__/integration/profile-create-page.test.js
  source/__tests__/integration/profile-metadata-requirements.test.js
  source/__tests__/integration/property-template-requirements.test.js
  source/__tests__/integration/resource-template-requirements.test.js
  source/__tests__/integration/select-resource-template-menu.test.js
Labels: M3

#221 propertyTemplate form: text box input for ResourceTemplate ID, not selector
  source/__tests__/integration/import-profile.test.js
  source/__tests__/integration/property-template-requirements.test.js
  source/html/template.html
Labels: M3

#224 add tests for new schema, bonus tests and refactoring
  source/__tests__/__fixtures__/place_profile_sinopia_v0.2.0.json
  source/__tests__/integration/edit-profile.test.js
  source/__tests__/integration/export-profile.test.js
  source/__tests__/integration/import-profile.test.js
  source/__tests__/integration/property-template-requirements.test.js
Labels: M3

#226 Bump version, add postpublish script to cut/push git tag, and update docs
  README.md
  package.json
Labels: M3
